# Generated by Django 2.2.4 on 2022-09-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
